### PR TITLE
Factor out split_filename/2

### PR DESCRIPTION
**Pull request by iilyak**
@eiri: Do not merge.
I'll push directly into `refactor-rename_on_delete` branch if you agree with the change.

### CODE REVIEW

**Comment by eiri** [comment]
To be honest I don't find your version much clearer on what it is doing or more idiomatic than mine foldl. It might be jiffy faster, but we are talking about traversing 5-6 elements list, I don't think it worth to double loc for that. I guess we can refactor that tokenizer into its own function, though it's not like it's going to be used outside of deleted_filename. So what exactly is the gain of a hair splitting here?

**Comment by iilyak** [comment]
The current version is hard to understand. Apparently mine is not any better.

**Comment by eiri** [comment]
We don't have a formal definition for data dir hierarchy, it's half-configurable, "shards" prefix hardcoded all over fabric and for kicks is inconsistent, "mrview" prefix is _supposedly_ mrview engine's namespace, though I'm not 100% sure it is used even for search -- I don't think it's _possible_ to make this tokenizer easy to understand, which is partly why it'd better to stay incapsulated in deleted_filename. That's unless we are willing just damn encode the whole path into deleted filename. Which, after all of this bickering, doesn't sounds like a such silly idea anymore.

**Comment by iilyak** [comment]
Closing the PR to keep the discussion in a single place https://github.com/apache/couchdb-couch/pull/141

**Pull request closed without merging**
