### PR TITLE
45855 dbnext update

### PR DESCRIPTION
**Pull request by iilyak**
Update our fork from upstream. 

```
git remote add upstream https://github.com/apache/couchdb-couch.git
git fetch upstream master
git checkout 45855-dbnext
git rebase -i upstream/master
git push origin 45855-dbnext:45855-dbnext-update-1
```

### CODE REVIEW

**Comment by rnewson** [comment]
needs rebasing. title needs updating (remove numeric prefix).

**Comment by iilyak** [comment]
Rebased. I also removed following cloudant commits since we don't need them anymore:
- b9fffbf6ea5140f9573f0981868d33f7ffd3c23e: Rename couch_users_db:save into transform_doc
- a3f616cf770d9df20e020361faf28bd4736b0bd0: Export couch_users_db:transform_doc/1

**Comment by rnewson** [comment]
+1

**Comment by mikewallace1979** [comment]
Should this have been merged to master rather than 45855-dbnext (which had already been merged to master)?

**Comment by iilyak** [comment]
@mikewallace1979: We didn't merge it into master and we don't have plans to do so any time soon.

**Comment by mikewallace1979** [comment]
@iilyak Ok - I see that now, for some reason I thought 45855-dbnext had merged to master but it quite clearly hasn't :)

**Pull request merged**
